graph BT


subgraph 数据层
    Block1
    Block2
    Block3
    BlockN
    Note
    Note --- Block1
    Note --- Block2
    Note --- Block3
    Note --- BlockN
    NoteSelection
    NoteRange
    NoteRange --- NoteSelection
    BlockRange1 --- NoteRange
    BlockRange2 --- NoteRange
    BlockRange3 --- NoteRange
    BlockRangeM --- NoteRange
end

subgraph 视图层
    BlockView1
    BlockView2
    BlockView3
    BlockViewN
    NoteView
    BlockView1 --- NoteView
    BlockView2 --- NoteView
    BlockView3 --- NoteView
    BlockViewN --- NoteView
    NoteSelectionView
end

Block1 -.- BlockView1
Block2 -.- BlockView2
Block3 -.- BlockView3
BlockN -.- BlockViewN
NoteSelection -.- NoteSelectionView

style NoteSelection  fill:#f9f,stroke:#333;
style NoteSelectionView  fill:#f9f,stroke:#333;
