graph LR

c((Command))
ns((NoteSelection))
nsv[NoteSelectionView]
n((Note))
nv[NoteView]
ctrl{Controller}

c -->|修改|n
n -->|更新| nv
ctrl -->|操作抽象| c

c -->|endNoteRange| ns
ns -->|startNoteRange| c
nv -->|交互| ctrl
ctrl -->|选区变化| ns
ns -->|更新| nsv


style nv fill:#fcf,stroke:#333;
style nsv fill:#fcf,stroke:#333;
style c  fill:#ffc,stroke:#333;
style n  stroke:#333;
style ns  stroke:#333;
style ctrl  stroke:#333;
